version: "3.8"
services:
  nike-website:
    image: nginx:alpine
    container_name: nike-website
    ports:
      - "2222:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped
